# Generated by Django 4.1.7 on 2023-02-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_author_category_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="app.profile",
            ),
        ),
    ]
